export const DataProduct = [
  {
    title: "Apple",
    img: require("../assets/apple.png"),
    kilo: 1,
    price: 2.5,
    id: 1,
    description:
      "They are known for their crispness and diverse varieties, such as Gala, Fuji, and Granny Smith.",
    organicPercentage: "100%",
    expirationDate: "2 weeks",
    rating: "8.4",
    grm: "80 kcal",
  },
  {
    title: "Broccoli",
    img: require("../assets/brocoli.png"),
    kilo: 1,
    price: 3.5,
    id: 2,
    description:
      "Broccoli is a nutritious cruciferous vegetable, rich in vitamins, fiber, and antioxidants. Its vibrant green florets make it a versatile and healthy addition to various dishes.",
    organicPercentage: "100%",
    expirationDate: "1 week",
    rating: "8.4",
    grm: "80 kcal",
  },
  {
    title: "Cheese",
    img: require("../assets/cheese.png"),
    kilo: 1,
    price: 7.99,
    id: 3,
    description:
      "Cheese is a diverse dairy product with numerous varieties, textures, and flavors. It adds richness and depth to various cuisines worldwide.",
    organicPercentage: "100%",
    expirationDate: "1 month",
    rating: "8.4",
    grm: "80 kcal",
  },
  {
    title: "Meat",
    img: require("../assets/meat-science-review.png"),
    kilo: 1,
    price: 15.99,
    id: 4,
    description:
      "Meat is a primary source of protein, essential for nutrition. It includes various types like beef, chicken, pork, and lamb, offering diverse culinary options.",
    organicPercentage: "100%",
    expirationDate: "1 week",
    rating: "8.4",
    grm: "80 kcal",
  },
  {
    title: "Green Grapes",
    img: require("../assets/green-grapes.png"),
    kilo: 1,
    price: 4.99,
    id: 5,
    description:
      "Green grapes are sweet and refreshing fruits. They are rich in vitamins, antioxidants, and contribute to a healthy diet and delicious snacks.",
    organicPercentage: "100%",
    expirationDate: "2 weeks",
    rating: "8.4",
    grm: "80 kcal",
  },
  {
    title: "Banana",
    img: require("../assets/Banana-Single.png"),
    kilo: 1,
    price: 1.99,
    id: 6,
    description:
      "Bananas are a popular fruit known for their natural sweetness and high potassium content. They are versatile, nutritious, and a convenient on-the-go snack.",
    organicPercentage: "100%",
    expirationDate: "1 week",
    rating: "8.4",
    grm: "80 kcal",
  },
  {
    title: "Bell Pepper",
    img: require("../assets/Bellpeper.png"),
    kilo: 1,
    price: 2.99,
    id: 7,
    description:
      "Bell peppers are colorful and crunchy vegetables. Available in various hues, they are rich in vitamins, adding flavor and nutrition to diverse culinary creations.",
    organicPercentage: "100%",
    expirationDate: "2 weeks",
    rating: "8.4",
    grm: "80 kcal",
  },
  {
    title: "Onion",
    img: require("../assets/onion.png"),
    kilo: 1,
    price: 1.49,
    id: 8,
    description:
      "Onions are pungent, flavorful bulbs widely used in cooking. Available in various types, they add depth and aroma to a myriad of dishes.",
    organicPercentage: "100%",
    expirationDate: "1 month",
    rating: "8.4",
    grm: "80 kcal",
  },
  {
    title: "Chicken",
    img: require("../assets/chicken_tigh.png"),
    kilo: 1,
    price: 12.99,
    id: 9,
    description:
      "Chicken is a versatile and widely consumed meat, known for its lean protein content. It's a staple in various cuisines, offering diverse preparation methods.",
    organicPercentage: "100%",
    expirationDate: "1 week",
    rating: "8.4",
    grm: "80 kcal",
  },
];
