export const DataProduct = [
  {
    title: "apple",
    img: require("../assets/apple.png"),
    kilo: 1,
    price: 1,
    id: 1,
  },
  {
    title: "brocoli",
    img: require("../assets/brocoli.png"),
    kilo: 1,
    price: 2,
    id: 2,
  },
  {
    title: "cheese",
    img: require("../assets/cheese.png"),
    kilo: 1,
    price: 1,
    id: 3,
  },
  {
    title: "meat",
    img: require("../assets/meat-science-review.png"),
    kilo: 1,
    price: 45,
    id: 4,
  },
  {
    title: "green-grapes",
    img: require("../assets/green-grapes.png"),
    kilo: 1,
    price: 1,
    id: 5,
  },
  {
    title: "banana",
    img: require("../assets/Banana-Single.png"),
    kilo: 1,
    price: 2,
    id: 6,
  },
  {
    title: "bell pepper",
    img: require("../assets/Bellpeper.png"),
    kilo: 1,
    price: 2,
    id: 7,
  },
  {
    title: "onion",
    img: require("../assets/onion.png"),
    kilo: 1,
    price: 2,
    id: 8,
  },
  {
    title: "meat",
    img: require("../assets/chicken_tigh.png"),
    kilo: 1,
    price: 30,
    id: 9,
  },
];
